# Generated by Django 6.0.4 on 2026-04-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marmitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marmita',
            name='peso',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
