# Generated by Django 6.0.4 on 2026-04-28 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marmitas', '0002_marmita_peso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marmita',
            name='user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marmita',
            name='descricao',
            field=models.TextField(max_length=260),
        ),
        migrations.AlterField(
            model_name='marmita',
            name='ingredientes',
            field=models.TextField(max_length=260),
        ),
    ]
