# Generated by Django 6.0.4 on 2026-04-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marmitas', '0003_marmita_user_alter_marmita_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marmita',
            name='descricao',
            field=models.TextField(max_length=360),
        ),
        migrations.AlterField(
            model_name='marmita',
            name='ingredientes',
            field=models.TextField(max_length=360),
        ),
    ]
