# Generated by Django 6.0.4 on 2026-05-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marmitas', '0004_alter_marmita_descricao_alter_marmita_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='marmita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='marmitas/imagens/'),
        ),
    ]
