# Generated by Django 6.0.4 on 2026-05-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marmitas', '0005_marmita_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marmita',
            name='imagem',
            field=models.ImageField(upload_to='marmitas/imagens/'),
        ),
    ]
